import { Property } from "@shared/schema";

// Dummy property data for development and testing
export const dummyProperties: Property[] = [
  {
    id: 1,
    title: "Luxury 2BR Apartment in Downtown Dubai",
    unit_kind: "listing",
    transaction_type: "sale",
    property_type: "residential",
    beds: "2",
    baths: 2,
    area_sqft: 1200,
    price: "1500000",
    community: "downtown",
    location: "Downtown Dubai, Burj Khalifa District",
    description: "Stunning 2-bedroom apartment with panoramic views of Burj Khalifa and Dubai Fountain. Premium finishes, floor-to-ceiling windows, and access to world-class amenities including infinity pool, gym, and concierge services.",
    off_plan: false,
    distressed: false,
    property_id: "DD-2BR-001",
    updated_at: new Date("2024-12-15T10:30:00Z"),
    created_at: new Date("2024-12-10T09:00:00Z"),
  },
  {
    id: 2,
    title: "Modern 1BR in Dubai Marina",
    unit_kind: "client_request",
    transaction_type: "rent",
    property_type: "residential",
    beds: "1",
    baths: 1,
    area_sqft: 800,
    price: "85000",
    community: "marina",
    location: "Dubai Marina, Marina Walk",
    description: "Contemporary 1-bedroom apartment in prime Marina location. Fully furnished with modern appliances, balcony with marina views, and walking distance to beach, restaurants, and metro station.",
    off_plan: false,
    distressed: false,
    property_id: "DM-1BR-002",
    updated_at: new Date("2024-12-14T15:45:00Z"),
    created_at: new Date("2024-12-08T11:20:00Z"),
  },
  {
    id: 3,
    title: "Spacious 4BR Villa in Palm Jumeirah",
    unit_kind: "listing",
    transaction_type: "sale",
    property_type: "residential",
    beds: "4",
    baths: 5,
    area_sqft: 3500,
    price: "8500000",
    community: "palm",
    location: "Palm Jumeirah, Frond G",
    description: "Exclusive 4-bedroom villa on Palm Jumeirah with private beach access. Features include private pool, garden, maid's room, and spectacular views of Dubai skyline and Arabian Gulf.",
    off_plan: false,
    distressed: false,
    property_id: "PJ-4BR-003",
    updated_at: new Date("2024-12-13T08:20:00Z"),
    created_at: new Date("2024-12-05T14:30:00Z"),
  },
  {
    id: 4,
    title: "Studio Apartment in Business Bay",
    unit_kind: "client_request",
    transaction_type: "rent",
    property_type: "residential",
    beds: "studio",
    baths: 1,
    area_sqft: 450,
    price: "55000",
    community: "business-bay",
    location: "Business Bay, Bay Square",
    description: "Compact and efficient studio apartment in the heart of Business Bay. Perfect for young professionals, featuring modern design, built-in storage, and close proximity to metro and business district.",
    off_plan: false,
    distressed: false,
    property_id: "BB-ST-004",
    updated_at: new Date("2024-12-12T12:15:00Z"),
    created_at: new Date("2024-12-01T16:45:00Z"),
  },
  {
    id: 5,
    title: "Penthouse 3BR in JBR with Sea View",
    unit_kind: "listing",
    transaction_type: "sale",
    property_type: "residential",
    beds: "3",
    baths: 4,
    area_sqft: 2200,
    price: "4200000",
    community: "jbr",
    location: "Jumeirah Beach Residence, Cluster A",
    description: "Magnificent penthouse with unobstructed sea views from every room. Features include private terrace, jacuzzi, premium finishes, and direct beach access. Resort-style living in the heart of JBR.",
    off_plan: false,
    distressed: false,
    property_id: "JBR-3BR-005",
    updated_at: new Date("2024-12-11T09:30:00Z"),
    created_at: new Date("2024-11-28T13:20:00Z"),
  },
  {
    id: 6,
    title: "Off-Plan 2BR Townhouse in New Development",
    unit_kind: "client_request",
    transaction_type: "sale",
    property_type: "residential",
    beds: "2",
    baths: 3,
    area_sqft: 1800,
    price: "1850000",
    community: "downtown",
    location: "Downtown Dubai, New Creek Harbour",
    description: "Brand new off-plan townhouse in exclusive development. Modern architecture, private garden, covered parking, and community amenities including parks, retail, and schools. Completion Q3 2025.",
    off_plan: true,
    distressed: false,
    property_id: "DD-TH-006",
    updated_at: new Date("2024-12-10T14:20:00Z"),
    created_at: new Date("2024-11-25T10:15:00Z"),
  },
  {
    id: 7,
    title: "Distressed Sale: 1BR in Business Bay",
    unit_kind: "listing",
    transaction_type: "sale",
    property_type: "residential",
    beds: "1",
    baths: 1,
    area_sqft: 750,
    price: "750000",
    community: "business-bay",
    location: "Business Bay, Executive Tower",
    description: "Urgent sale required - 1-bedroom apartment at below market value. Property requires minor renovation but offers excellent investment opportunity in prime Business Bay location with canal views.",
    off_plan: false,
    distressed: true,
    property_id: "BB-1BR-007",
    updated_at: new Date("2024-12-09T16:45:00Z"),
    created_at: new Date("2024-11-20T11:30:00Z"),
  },
  {
    id: 8,
    title: "Commercial Office Space in DIFC",
    unit_kind: "client_request",
    transaction_type: "rent",
    property_type: "commercial",
    beds: null,
    baths: 2,
    area_sqft: 1500,
    price: "180000",
    community: "business-bay",
    location: "Dubai International Financial Centre, Gate District",
    description: "Premium commercial office space in prestigious DIFC location. Fully fitted with modern interiors, meeting rooms, and access to business center facilities. Perfect for financial services and consulting firms.",
    off_plan: false,
    distressed: false,
    property_id: "DIFC-OF-008",
    updated_at: new Date("2024-12-08T11:00:00Z"),
    created_at: new Date("2024-11-15T09:45:00Z"),
  },
  {
    id: 9,
    title: "5+ Bedroom Villa in Emirates Hills",
    unit_kind: "listing",
    transaction_type: "sale",
    property_type: "residential",
    beds: "5+",
    baths: 7,
    area_sqft: 8500,
    price: "25000000",
    community: "downtown",
    location: "Emirates Hills, Sector E",
    description: "Ultra-luxury 6-bedroom villa in exclusive Emirates Hills. Features include private elevator, wine cellar, home theater, gym, spa, infinity pool, and staff quarters. Golf course views and 24/7 security.",
    off_plan: false,
    distressed: false,
    property_id: "EH-6BR-009",
    updated_at: new Date("2024-12-07T13:30:00Z"),
    created_at: new Date("2024-11-10T15:20:00Z"),
  },
  {
    id: 10,
    title: "Affordable 3BR Apartment for Rent",
    unit_kind: "client_request",
    transaction_type: "rent",
    property_type: "residential",
    beds: "3",
    baths: 2,
    area_sqft: 1400,
    price: "95000",
    community: "marina",
    location: "Dubai Marina, Marina Heights",
    description: "Spacious 3-bedroom apartment perfect for families. Features include built-in wardrobes, balcony with partial marina views, shared pool and gym facilities. Close to schools and shopping centers.",
    off_plan: false,
    distressed: false,
    property_id: "DM-3BR-010",
    updated_at: new Date("2024-12-06T10:15:00Z"),
    created_at: new Date("2024-11-05T12:40:00Z"),
  }
];

// Filter properties based on search criteria
export function filterDummyProperties(filters: any) {
  return dummyProperties.filter(property => {
    // Required filters
    if (filters.unit_kind && property.unit_kind !== filters.unit_kind) return false;
    if (filters.transaction_type && property.transaction_type !== filters.transaction_type) return false;
    
    // Optional filters
    if (filters.property_type && property.property_type !== filters.property_type) return false;
    if (filters.beds && property.beds !== filters.beds) return false;
    if (filters.area_sqft_min && property.area_sqft && property.area_sqft < filters.area_sqft_min) return false;
    if (filters.area_sqft_max && property.area_sqft && property.area_sqft > filters.area_sqft_max) return false;
    if (filters.price_min && parseFloat(property.price) < filters.price_min) return false;
    if (filters.price_max && parseFloat(property.price) > filters.price_max) return false;
    if (filters.community && property.community !== filters.community) return false;
    if (filters.off_plan !== undefined && property.off_plan !== filters.off_plan) return false;
    if (filters.distressed !== undefined && property.distressed !== filters.distressed) return false;
    
    return true;
  });
}